project:
  type: website

website:
  title: "MLB Data Analysis Blog"
  site-url: "https://yasumorishima.github.io/quarto-blog"
  description: "Baseball analytics and Kaggle datasets"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/yasumorishima
      - text: Kaggle
        href: https://www.kaggle.com/yasunorim

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
